//TTS function IDs

#ifndef TTSID_H
#define TTSID_H

#define ID_TTS_SPEAKDOC 0xEB00
#define ID_TTS_SPEAKSEL 0xEB01
#define ID_TTS_PAUSE 0xEB02
#define ID_TTS_STOP 0xEB03
#define ID_TTS_CREATEWAV 0xEB04
#define ID_TTS_CREATELOG 0xEB05
#define ID_TTS_CREATERAW 0xEB06
#define ID_TTS_RESET 0xEB07
#define ID_TTS_LOADDICT 0xEB08
#define ID_TTS_UNLOADDICT 0xEB09
#define ID_TTS_VERSION 0xEB0A
#define ID_TTS_RATEUP 0xEB0B
#define ID_TTS_RATEDOWN 0xEB0C
#define ID_TTS_NEXTVOICE 0xEB0D
#define ID_TTS_PREVVOICE 0xEB0E
#define ID_TTS_SETTINGS 0xEB0F
#define ID_TTS_LOADDLL 0xEB10

#define IDC_DEVICE 201
#define IDC_OWN 202
#define IDC_FORMAT 203
#define IDC_LOGMODE 204
#define IDC_STARTSPEAK 205
#define IDC_STARTMSG 206

#endif
